spring:
  datasource:
    url: jdbc:log4jdbc:mysql://222.122.235.22:3306/allra?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: allra
    password: Allra0001!
#    hikari:
#      auto-commit: true
#      connection-test-query: SELECT 1
#      idle-timeout: 30000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      pool-name: allradbcp


server:
  port: 9091